################################################################################
#
# This file is a part of the package: MatrixAlgorithms
# Released under the MIT license, see LICENSE file for details.
# Copyright (C) 2023 Aravindh Krishnamoorthy and contributors.
#
################################################################################

import Base: sqrt
using LinearAlgebra

################################################################################
#
# Square root of a matrix
# Reference [1]: Smith, M. I. (2003). A Schur Algorithm for Computing Matrix pth Roots.
#   SIAM Journal on Matrix Analysis and Applications (Vol. 24, Issue 4, pp. 971–989).
#   https://doi.org/10.1137/s0895479801392697
#
# NOTE: The matrix is lifted to the complex field if the diagonal values of the
#         triangular Schur matrix does not have a square root in type T
#
################################################################################
function sqrtm(A::AbstractMatrix{T}; atol::Real = 0,
               rtol::Real = min(size(A)...)*eps(real(float(one(T))))) where {T}
    m, n = size(A)
    (m == n) || throw(ArgumentError("sqrt: Matrix A must be square."))
    symmetric = ishermitian(A)
    if symmetric
        e, V = eigen(A)
        negative = any(e .< 0)
        if negative
            Q = Diagonal(sqrt.(complex.(e)))
            if isreal(V)
                return complex.(V*real(Q)*V', V*imag(Q)*V')
            else
                return V*Q*V'
            end
        else
            Q = Diagonal(sqrt.(e))
            return V*Q*V'
        end
    elseif isreal(A)
        S = schur(real(A))
        scale_vals = isempty(S.values) ? zero(real(float(one(T)))) : maximum(abs, S.values)
        scale_mat  = opnorm(real(A), 1)
        scale = max(scale_vals, scale_mat)
        tol = max(atol, rtol*scale)
        negative = false
        for i = 1:n
            if isreal(S.values[i]) && real(S.values[i]) < -tol
                negative = true
                break
            end
        end
        rankA = count(λ -> abs(λ) > tol, S.values)
        use_gantmacher = rankA < n - 1
        if negative || use_gantmacher
            S = Schur{Complex}(S)
        end
        if use_gantmacher
            return S.Z * gantmacher!(S.T; atol=atol, rtol=rtol) * S.Z'
        else
            return S.Z * trsr!(S.T) * S.Z'
        end
    else
        S = schur(A)
        scale_vals = isempty(S.values) ? zero(real(float(one(T)))) : maximum(abs, S.values)
        scale_mat  = opnorm(A, 1)
        scale = max(scale_vals, scale_mat)
        tol = max(atol, rtol*scale)
        rankA = count(λ -> abs(λ) > tol, S.values)
        if rankA < n - 1
            return S.Z * gantmacher!(S.T; atol=atol, rtol=rtol) * S.Z'
        else
            return S.Z * trsr!(S.T) * S.Z'
        end
    end
end

################################################################################
#
# Square root of a matrix using Gantmacher's algorithm
# Reference [2]: Gantmacher, F. R. The Theory of Matrices. Vol. 2, Chapter VIII, Sec. 7.
# NOTE: Jordan form version (numerically unstable) for singular/rank-deficient inputs
#       and will need to be improved.
# NOTE: This first version of the code was generated by ChatGPT 5.2 Thinking
# NOTE: The function was modified to use Schur output instead of Jordon form by
#       ChatGPT 5.2 Thinking
#
################################################################################
function gantmacher!(A::AbstractMatrix{T}; atol::Real = 0,
                     rtol::Real = min(size(A)...)*eps(real(float(one(T))))) where {T}
    m, n = size(A)
    (m == n) || throw(ArgumentError("gantmacher!: Matrix A must be square."))

    RT = typeof(real(float(one(T))))
    Tc = Complex{RT}
    Ac = Matrix{Tc}(A)

    S = schur(Ac)
    scale_vals = isempty(S.values) ? zero(RT) : maximum(abs, S.values)
    scale_mat  = opnorm(Ac, 1)
    scale = max(scale_vals, scale_mat)
    tol0 = max(atol, rtol * scale)
    select = map(λ -> abs(λ) > tol0, S.values)
    S = ordschur(S, select)

    r = count(select)
    Tord = Matrix{Tc}(S.T)
    Qord = Matrix{Tc}(S.Z)

    if r == n
        return Qord * trsr!(copy(Tord)) * Qord'
    end

    local T1, T0, B
    if r == 0
        T1 = zeros(Tc, 0, 0)
        T0 = Tord
        B = zeros(Tc, 0, n)
    else
        T1 = Tord[1:r, 1:r]
        T0 = Tord[r+1:n, r+1:n]
        B = Tord[1:r, r+1:n]
    end

    U1 = r == 0 ? zeros(Tc, 0, 0) : trsr!(copy(T1))

    m0 = size(T0, 1)
    if m0 == 0
        return Qord * U1 * Qord'
    end

    K = Vector{Matrix{Tc}}(undef, m0 + 1)
    ν = zeros(Int, m0 + 1)
    K[1] = zeros(Tc, m0, 0)
    ν[1] = 0

    Pk = Matrix{Tc}(I, m0, m0)
    stabilized = false
    for k = 1:m0
        Pk = Pk * T0
        N = nullspace(Pk; atol=atol, rtol=rtol)
        K[k+1] = Matrix{Tc}(N)
        ν[k+1] = size(N, 2)
        if ν[k+1] == m0
            for j = k+1:m0
                K[j+1] = K[k+1]
                ν[j+1] = m0
            end
            stabilized = true
            break
        end
    end
    stabilized || throw(ArgumentError("gantmacher!: failed to identify a numerically nilpotent zero-primary block."))

    d = zeros(Int, m0)
    for k = 1:m0
        d[k] = ν[k+1] - ν[k]
    end

    b = zeros(Int, m0)
    for k = 1:m0-1
        b[k] = d[k] - d[k+1]
    end
    b[m0] = d[m0]

    powers = Vector{Matrix{Tc}}(undef, m0 + 1)
    powers[1] = Matrix{Tc}(I, m0, m0)
    for k = 1:m0
        powers[k+1] = powers[k] * T0
    end

    heads = [zeros(Tc, m0, 0) for _ = 1:m0]
    for k = m0:-1:1
        need = b[k]
        need == 0 && continue

        G = zeros(Tc, m0, 0)
        for j = k+1:m0
            if size(heads[j], 2) > 0
                G = hcat(G, powers[j-k+1] * heads[j])
            end
        end

        Sspan = size(K[k], 2) == 0 ? G : (size(G, 2) == 0 ? K[k] : hcat(K[k], G))

        Bc = Matrix{Tc}(K[k+1])
        Sc = Matrix{Tc}(Sspan)
        size(Bc, 2) == 0 && throw(ArgumentError("gantmacher!: numerically ambiguous nilpotent chain structure."))

        local Sorth
        if size(Sc, 2) > 0
            U, σ, _ = svd(Sc; full=false)
            tolS = max(atol, rtol * (isempty(σ) ? zero(RT) : maximum(abs, σ)))
            rs = count(x -> abs(x) > tolS, σ)
            Sorth = rs == 0 ? zeros(Tc, size(Sc, 1), 0) : U[:, 1:rs]
        else
            Sorth = zeros(Tc, size(Bc, 1), 0)
        end

        Y = copy(Bc)
        if size(Sorth, 2) > 0
            Y .-= Sorth * (Sorth' * Y)
        end

        U, σ, _ = svd(Y; full=false)
        tolY = max(atol, rtol * (isempty(σ) ? zero(RT) : maximum(abs, σ)))
        rloc = count(x -> abs(x) > tolY, σ)

        rloc < need && throw(ArgumentError("gantmacher!: numerically ambiguous nilpotent chain structure."))
        rloc = need

        heads[k] = rloc == 0 ? zeros(Tc, size(Bc, 1), 0) : U[:, 1:rloc]
    end

    chains = Vector{Vector{Tc}}()
    parts = Int[]
    for k = m0:-1:1
        H = heads[k]
        for j = 1:size(H, 2)
            h = H[:, j]
            for p = k-1:-1:0
                push!(chains, powers[p+1] * h)
            end
            push!(parts, k)
        end
    end

    length(chains) == 0 && throw(ArgumentError("gantmacher!: failed to construct any nilpotent chains."))

    V = hcat(chains...)
    size(V, 2) == m0 || throw(ArgumentError("gantmacher!: failed to construct a full nilpotent chain basis."))
    rank(V; atol=atol, rtol=rtol) < m0 && throw(ArgumentError("gantmacher!: numerically singular chain basis for the zero-primary block."))

    sort!(parts, rev=true)

    pieces = Matrix{Tc}[]
    i = 1
    while i <= length(parts)
        if i == length(parts)
            parts[i] == 1 || throw(ArgumentError("gantmacher!: inferred nilpotent block partition does not admit a square root."))
            push!(pieces, zeros(Tc, 1, 1))
            i += 1
        else
            s = parts[i]
            t = parts[i+1]
            (s - t <= 1) || throw(ArgumentError("gantmacher!: inferred nilpotent block partition does not admit a square root."))
            rpair = s + t
            Jnil = zeros(Tc, rpair, rpair)
            for ii = 1:rpair
                Jnil[ii, ii] = zero(Tc)
            end
            for ii = 1:rpair-1
                Jnil[ii, ii+1] = one(Tc)
            end
            perm = vcat(collect(1:2:rpair), collect(2:2:rpair))
            Pperm = zeros(Tc, rpair, rpair)
            for j = 1:rpair
                Pperm[perm[j], j] = one(Tc)
            end
            push!(pieces, Pperm' * Jnil * Pperm)
            i += 2
        end
    end

    Ntot = sum(size(Bi, 1) for Bi in pieces)
    YJ = zeros(Tc, Ntot, Ntot)
    p = 1
    for Bi in pieces
        q = p + size(Bi, 1) - 1
        YJ[p:q, p:q] .= Matrix{Tc}(Bi)
        p = q + 1
    end

    size(YJ, 1) == m0 || throw(ArgumentError("gantmacher!: internal size mismatch in nilpotent model block."))

    U0 = V * YJ / V

    if r == 0
        return Qord * U0 * Qord'
    end

    r1 = size(U1, 1)
    r0 = size(U0, 1)
    local Y
    if r1 == 0
        Y = zeros(Tc, 0, r0)
    elseif r0 == 0
        Y = zeros(Tc, r1, 0)
    else
        Ksys = kron(Matrix{Tc}(I, r0, r0), U1) + kron(transpose(U0), Matrix{Tc}(I, r1, r1))
        y = Ksys \ vec(Matrix{Tc}(B))
        Y = reshape(y, r1, r0)
    end

    Uord = zeros(Tc, n, n)
    Uord[1:r, 1:r] = U1
    Uord[1:r, r+1:n] = Y
    Uord[r+1:n, r+1:n] = U0

    X = Qord * Uord * Qord'

    A_scale = max(opnorm(Ac, 2), one(RT))
    res = opnorm(X * X - Ac, 2) / A_scale
    res <= max(sqrt(eps(RT)), 10 * max(atol, rtol)) ||
        throw(ArgumentError("gantmacher!: hybrid Schur-Gantmacher construction failed residual check."))

    return X
end
